version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 469563970583.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t py_web_app:latest .
      - docker tag py_web_app:latest 469563970583.dkr.ecr.us-east-1.amazonaws.com/py_web_app:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 469563970583.dkr.ecr.us-east-1.amazonaws.com/py_web_app:latest
